"""Create user table

Revision ID: 1c64b22c8ea1
Revises: 24541c00a0fa
Create Date: 2021-12-17 14:16:58.258018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c64b22c8ea1'
down_revision = '24541c00a0fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
