"""Create place table

Revision ID: ca89c870a0b0
Revises: 1c64b22c8ea1
Create Date: 2021-12-17 14:48:46.739044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca89c870a0b0'
down_revision = '1c64b22c8ea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
