"""Create place table

Revision ID: fcd3e01e17f4
Revises: 300be55ad020
Create Date: 2021-12-12 23:03:26.132351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd3e01e17f4'
down_revision = '300be55ad020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('nombre', sa.String(), nullable=True))
    op.add_column('places', sa.Column('precio', sa.Integer(), nullable=True))
    op.add_column('places', sa.Column('imagen', sa.String(), nullable=True))
    op.drop_index('ix_places_description', table_name='places')
    op.drop_index('ix_places_name', table_name='places')
    op.create_index(op.f('ix_places_nombre'), 'places', ['nombre'], unique=False)
    op.create_index(op.f('ix_places_precio'), 'places', ['precio'], unique=False)
    op.drop_column('places', 'image')
    op.drop_column('places', 'name')
    op.drop_column('places', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('places', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('places', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_places_precio'), table_name='places')
    op.drop_index(op.f('ix_places_nombre'), table_name='places')
    op.create_index('ix_places_name', 'places', ['name'], unique=False)
    op.create_index('ix_places_description', 'places', ['description'], unique=False)
    op.drop_column('places', 'imagen')
    op.drop_column('places', 'precio')
    op.drop_column('places', 'nombre')
    # ### end Alembic commands ###
